default:
  just --list

build:
  ./gradlew buildJvmLib

clean:
  rm -rf ../bdk-ffi/target/
  rm -rf ./build/
  rm -rf ./lib/build/
  rm -rf ./plugins/build/

publish-local:
  ./gradlew publishToMavenLocal -P localBuild

test:
  ./gradlew test

test-offline:
  ./gradlew test -P excludeConnectedTests

test-specific TEST:
  ./gradlew test --tests {{TEST}}