default:
  just --list

build-linux:
  bash ./scripts/build-linux-x86_64.sh

build-macos-aarch64:
  bash ./scripts/build-macos-aarch64.sh

build-macos-x86_64:
  bash ./scripts/build-macos-x86_64.sh
  
build-windows:
  bash ./scripts/build-windows-x86_64.sh

clean:
  rm -rf ../bdk-ffi/target/
  rm -rf ./build/
  rm -rf ./lib/build/

publish-local:
  ./gradlew publishToMavenLocal -P localBuild

test:
  ./gradlew test

test-offline:
  ./gradlew test -P excludeConnectedTests

test-specific TEST:
  ./gradlew test --tests {{TEST}}

build-docs:
  ./gradlew :lib:dokkaGeneratePublicationHtml
