package org.bitcoindevkit.bdk

enum class JnaError {
    InvalidU32Bytes,
    Generic,
    ScriptDoesntHaveAddressForm,
    SingleRecipientMultipleOutputs,
    SingleRecipientNoInputs,
    NoRecipients,
    NoUtxosSelected,
    OutputBelowDustLimit,
    InsufficientFunds,
    BnBTotalTriesExceeded,
    BnBNoExactMatch,
    UnknownUtxo,
    TransactionNotFound,
    TransactionConfirmed,
    IrreplaceableTransaction,
    FeeRateTooLow,
    FeeTooLow,
    MissingKeyOrigin,
    Key,
    ChecksumMismatch,
    SpendingPolicyRequired,
    InvalidPolicyPathError,
    Signer,
    InvalidProgressValue,
    ProgressUpdateError,
    InvalidOutpoint,
    Descriptor,
    AddressValidator,
    Encode,
    Miniscript,
    Bip32,
    Secp256k1,
    Json,
    Hex,
    Psbt,
    Electrum,

    //        Esplora
    //        CompactFilters
    Sled,
}