// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    uint64_t capacity;
    uint64_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H
#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t, int8_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
typedef void (*UniffiForeignFutureFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE
typedef struct UniffiForeignFuture {
    uint64_t handle;
    UniffiForeignFutureFree _Nonnull free;
} UniffiForeignFuture;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
typedef struct UniffiForeignFutureStructU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t, UniffiForeignFutureStructU8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
typedef struct UniffiForeignFutureStructI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t, UniffiForeignFutureStructI8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
typedef struct UniffiForeignFutureStructU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t, UniffiForeignFutureStructU16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
typedef struct UniffiForeignFutureStructI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t, UniffiForeignFutureStructI16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
typedef struct UniffiForeignFutureStructU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t, UniffiForeignFutureStructU32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
typedef struct UniffiForeignFutureStructI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t, UniffiForeignFutureStructI32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
typedef struct UniffiForeignFutureStructU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t, UniffiForeignFutureStructU64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
typedef struct UniffiForeignFutureStructI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t, UniffiForeignFutureStructI64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
typedef struct UniffiForeignFutureStructF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t, UniffiForeignFutureStructF32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
typedef struct UniffiForeignFutureStructF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t, UniffiForeignFutureStructF64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
typedef struct UniffiForeignFutureStructPointer {
    void*_Nonnull returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructPointer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
typedef void (*UniffiForeignFutureCompletePointer)(uint64_t, UniffiForeignFutureStructPointer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
typedef struct UniffiForeignFutureStructRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t, UniffiForeignFutureStructRustBuffer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
typedef struct UniffiForeignFutureStructVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureStructVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t, UniffiForeignFutureStructVoid
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FULL_SCAN_SCRIPT_INSPECTOR_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FULL_SCAN_SCRIPT_INSPECTOR_METHOD0
typedef void (*UniffiCallbackInterfaceFullScanScriptInspectorMethod0)(uint64_t, RustBuffer, uint32_t, void*_Nonnull, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_SYNC_SCRIPT_INSPECTOR_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_SYNC_SCRIPT_INSPECTOR_METHOD0
typedef void (*UniffiCallbackInterfaceSyncScriptInspectorMethod0)(uint64_t, void*_Nonnull, uint64_t, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_FULL_SCAN_SCRIPT_INSPECTOR
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_FULL_SCAN_SCRIPT_INSPECTOR
typedef struct UniffiVTableCallbackInterfaceFullScanScriptInspector {
    UniffiCallbackInterfaceFullScanScriptInspectorMethod0 _Nonnull inspect;
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
} UniffiVTableCallbackInterfaceFullScanScriptInspector;

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_SYNC_SCRIPT_INSPECTOR
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_SYNC_SCRIPT_INSPECTOR
typedef struct UniffiVTableCallbackInterfaceSyncScriptInspector {
    UniffiCallbackInterfaceSyncScriptInspectorMethod0 _Nonnull inspect;
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
} UniffiVTableCallbackInterfaceSyncScriptInspector;

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CLONE_ADDRESS
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CLONE_ADDRESS
void*_Nonnull uniffi_bdkffi_fn_clone_address(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_FREE_ADDRESS
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_FREE_ADDRESS
void uniffi_bdkffi_fn_free_address(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_ADDRESS_NEW
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_ADDRESS_NEW
void*_Nonnull uniffi_bdkffi_fn_constructor_address_new(RustBuffer address, RustBuffer network, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_ADDRESS_AS_STRING
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_ADDRESS_AS_STRING
RustBuffer uniffi_bdkffi_fn_method_address_as_string(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_ADDRESS_IS_VALID_FOR_NETWORK
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_ADDRESS_IS_VALID_FOR_NETWORK
int8_t uniffi_bdkffi_fn_method_address_is_valid_for_network(void*_Nonnull ptr, RustBuffer network, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_ADDRESS_NETWORK
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_ADDRESS_NETWORK
RustBuffer uniffi_bdkffi_fn_method_address_network(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_ADDRESS_SCRIPT_PUBKEY
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_ADDRESS_SCRIPT_PUBKEY
void*_Nonnull uniffi_bdkffi_fn_method_address_script_pubkey(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_ADDRESS_TO_QR_URI
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_ADDRESS_TO_QR_URI
RustBuffer uniffi_bdkffi_fn_method_address_to_qr_uri(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CLONE_AMOUNT
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CLONE_AMOUNT
void*_Nonnull uniffi_bdkffi_fn_clone_amount(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_FREE_AMOUNT
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_FREE_AMOUNT
void uniffi_bdkffi_fn_free_amount(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_AMOUNT_FROM_BTC
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_AMOUNT_FROM_BTC
void*_Nonnull uniffi_bdkffi_fn_constructor_amount_from_btc(double from_btc, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_AMOUNT_FROM_SAT
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_AMOUNT_FROM_SAT
void*_Nonnull uniffi_bdkffi_fn_constructor_amount_from_sat(uint64_t from_sat, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_AMOUNT_TO_BTC
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_AMOUNT_TO_BTC
double uniffi_bdkffi_fn_method_amount_to_btc(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_AMOUNT_TO_SAT
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_AMOUNT_TO_SAT
uint64_t uniffi_bdkffi_fn_method_amount_to_sat(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CLONE_BUMPFEETXBUILDER
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CLONE_BUMPFEETXBUILDER
void*_Nonnull uniffi_bdkffi_fn_clone_bumpfeetxbuilder(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_FREE_BUMPFEETXBUILDER
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_FREE_BUMPFEETXBUILDER
void uniffi_bdkffi_fn_free_bumpfeetxbuilder(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_BUMPFEETXBUILDER_NEW
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_BUMPFEETXBUILDER_NEW
void*_Nonnull uniffi_bdkffi_fn_constructor_bumpfeetxbuilder_new(RustBuffer txid, void*_Nonnull fee_rate, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_BUMPFEETXBUILDER_ENABLE_RBF
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_BUMPFEETXBUILDER_ENABLE_RBF
void*_Nonnull uniffi_bdkffi_fn_method_bumpfeetxbuilder_enable_rbf(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_BUMPFEETXBUILDER_ENABLE_RBF_WITH_SEQUENCE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_BUMPFEETXBUILDER_ENABLE_RBF_WITH_SEQUENCE
void*_Nonnull uniffi_bdkffi_fn_method_bumpfeetxbuilder_enable_rbf_with_sequence(void*_Nonnull ptr, uint32_t nsequence, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_BUMPFEETXBUILDER_FINISH
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_BUMPFEETXBUILDER_FINISH
void*_Nonnull uniffi_bdkffi_fn_method_bumpfeetxbuilder_finish(void*_Nonnull ptr, void*_Nonnull wallet, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CLONE_DERIVATIONPATH
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CLONE_DERIVATIONPATH
void*_Nonnull uniffi_bdkffi_fn_clone_derivationpath(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_FREE_DERIVATIONPATH
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_FREE_DERIVATIONPATH
void uniffi_bdkffi_fn_free_derivationpath(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_DERIVATIONPATH_NEW
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_DERIVATIONPATH_NEW
void*_Nonnull uniffi_bdkffi_fn_constructor_derivationpath_new(RustBuffer path, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CLONE_DESCRIPTOR
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CLONE_DESCRIPTOR
void*_Nonnull uniffi_bdkffi_fn_clone_descriptor(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_FREE_DESCRIPTOR
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_FREE_DESCRIPTOR
void uniffi_bdkffi_fn_free_descriptor(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_DESCRIPTOR_NEW
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_DESCRIPTOR_NEW
void*_Nonnull uniffi_bdkffi_fn_constructor_descriptor_new(RustBuffer descriptor, RustBuffer network, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_DESCRIPTOR_NEW_BIP44
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_DESCRIPTOR_NEW_BIP44
void*_Nonnull uniffi_bdkffi_fn_constructor_descriptor_new_bip44(void*_Nonnull secret_key, RustBuffer keychain, RustBuffer network, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_DESCRIPTOR_NEW_BIP44_PUBLIC
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_DESCRIPTOR_NEW_BIP44_PUBLIC
void*_Nonnull uniffi_bdkffi_fn_constructor_descriptor_new_bip44_public(void*_Nonnull public_key, RustBuffer fingerprint, RustBuffer keychain, RustBuffer network, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_DESCRIPTOR_NEW_BIP49
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_DESCRIPTOR_NEW_BIP49
void*_Nonnull uniffi_bdkffi_fn_constructor_descriptor_new_bip49(void*_Nonnull secret_key, RustBuffer keychain, RustBuffer network, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_DESCRIPTOR_NEW_BIP49_PUBLIC
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_DESCRIPTOR_NEW_BIP49_PUBLIC
void*_Nonnull uniffi_bdkffi_fn_constructor_descriptor_new_bip49_public(void*_Nonnull public_key, RustBuffer fingerprint, RustBuffer keychain, RustBuffer network, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_DESCRIPTOR_NEW_BIP84
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_DESCRIPTOR_NEW_BIP84
void*_Nonnull uniffi_bdkffi_fn_constructor_descriptor_new_bip84(void*_Nonnull secret_key, RustBuffer keychain, RustBuffer network, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_DESCRIPTOR_NEW_BIP84_PUBLIC
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_DESCRIPTOR_NEW_BIP84_PUBLIC
void*_Nonnull uniffi_bdkffi_fn_constructor_descriptor_new_bip84_public(void*_Nonnull public_key, RustBuffer fingerprint, RustBuffer keychain, RustBuffer network, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_DESCRIPTOR_NEW_BIP86
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_DESCRIPTOR_NEW_BIP86
void*_Nonnull uniffi_bdkffi_fn_constructor_descriptor_new_bip86(void*_Nonnull secret_key, RustBuffer keychain, RustBuffer network, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_DESCRIPTOR_NEW_BIP86_PUBLIC
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_DESCRIPTOR_NEW_BIP86_PUBLIC
void*_Nonnull uniffi_bdkffi_fn_constructor_descriptor_new_bip86_public(void*_Nonnull public_key, RustBuffer fingerprint, RustBuffer keychain, RustBuffer network, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_DESCRIPTOR_AS_STRING
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_DESCRIPTOR_AS_STRING
RustBuffer uniffi_bdkffi_fn_method_descriptor_as_string(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_DESCRIPTOR_AS_STRING_PRIVATE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_DESCRIPTOR_AS_STRING_PRIVATE
RustBuffer uniffi_bdkffi_fn_method_descriptor_as_string_private(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CLONE_DESCRIPTORPUBLICKEY
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CLONE_DESCRIPTORPUBLICKEY
void*_Nonnull uniffi_bdkffi_fn_clone_descriptorpublickey(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_FREE_DESCRIPTORPUBLICKEY
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_FREE_DESCRIPTORPUBLICKEY
void uniffi_bdkffi_fn_free_descriptorpublickey(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_DESCRIPTORPUBLICKEY_FROM_STRING
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_DESCRIPTORPUBLICKEY_FROM_STRING
void*_Nonnull uniffi_bdkffi_fn_constructor_descriptorpublickey_from_string(RustBuffer public_key, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_DESCRIPTORPUBLICKEY_AS_STRING
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_DESCRIPTORPUBLICKEY_AS_STRING
RustBuffer uniffi_bdkffi_fn_method_descriptorpublickey_as_string(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_DESCRIPTORPUBLICKEY_DERIVE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_DESCRIPTORPUBLICKEY_DERIVE
void*_Nonnull uniffi_bdkffi_fn_method_descriptorpublickey_derive(void*_Nonnull ptr, void*_Nonnull path, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_DESCRIPTORPUBLICKEY_EXTEND
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_DESCRIPTORPUBLICKEY_EXTEND
void*_Nonnull uniffi_bdkffi_fn_method_descriptorpublickey_extend(void*_Nonnull ptr, void*_Nonnull path, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CLONE_DESCRIPTORSECRETKEY
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CLONE_DESCRIPTORSECRETKEY
void*_Nonnull uniffi_bdkffi_fn_clone_descriptorsecretkey(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_FREE_DESCRIPTORSECRETKEY
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_FREE_DESCRIPTORSECRETKEY
void uniffi_bdkffi_fn_free_descriptorsecretkey(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_DESCRIPTORSECRETKEY_FROM_STRING
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_DESCRIPTORSECRETKEY_FROM_STRING
void*_Nonnull uniffi_bdkffi_fn_constructor_descriptorsecretkey_from_string(RustBuffer secret_key, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_DESCRIPTORSECRETKEY_NEW
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_DESCRIPTORSECRETKEY_NEW
void*_Nonnull uniffi_bdkffi_fn_constructor_descriptorsecretkey_new(RustBuffer network, void*_Nonnull mnemonic, RustBuffer password, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_DESCRIPTORSECRETKEY_AS_PUBLIC
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_DESCRIPTORSECRETKEY_AS_PUBLIC
void*_Nonnull uniffi_bdkffi_fn_method_descriptorsecretkey_as_public(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_DESCRIPTORSECRETKEY_AS_STRING
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_DESCRIPTORSECRETKEY_AS_STRING
RustBuffer uniffi_bdkffi_fn_method_descriptorsecretkey_as_string(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_DESCRIPTORSECRETKEY_DERIVE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_DESCRIPTORSECRETKEY_DERIVE
void*_Nonnull uniffi_bdkffi_fn_method_descriptorsecretkey_derive(void*_Nonnull ptr, void*_Nonnull path, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_DESCRIPTORSECRETKEY_EXTEND
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_DESCRIPTORSECRETKEY_EXTEND
void*_Nonnull uniffi_bdkffi_fn_method_descriptorsecretkey_extend(void*_Nonnull ptr, void*_Nonnull path, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_DESCRIPTORSECRETKEY_SECRET_BYTES
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_DESCRIPTORSECRETKEY_SECRET_BYTES
RustBuffer uniffi_bdkffi_fn_method_descriptorsecretkey_secret_bytes(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CLONE_ELECTRUMCLIENT
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CLONE_ELECTRUMCLIENT
void*_Nonnull uniffi_bdkffi_fn_clone_electrumclient(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_FREE_ELECTRUMCLIENT
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_FREE_ELECTRUMCLIENT
void uniffi_bdkffi_fn_free_electrumclient(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_ELECTRUMCLIENT_NEW
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_ELECTRUMCLIENT_NEW
void*_Nonnull uniffi_bdkffi_fn_constructor_electrumclient_new(RustBuffer url, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_ELECTRUMCLIENT_BROADCAST
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_ELECTRUMCLIENT_BROADCAST
RustBuffer uniffi_bdkffi_fn_method_electrumclient_broadcast(void*_Nonnull ptr, void*_Nonnull transaction, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_ELECTRUMCLIENT_FULL_SCAN
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_ELECTRUMCLIENT_FULL_SCAN
void*_Nonnull uniffi_bdkffi_fn_method_electrumclient_full_scan(void*_Nonnull ptr, void*_Nonnull full_scan_request, uint64_t stop_gap, uint64_t batch_size, int8_t fetch_prev_txouts, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_ELECTRUMCLIENT_SYNC
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_ELECTRUMCLIENT_SYNC
void*_Nonnull uniffi_bdkffi_fn_method_electrumclient_sync(void*_Nonnull ptr, void*_Nonnull sync_request, uint64_t batch_size, int8_t fetch_prev_txouts, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CLONE_ESPLORACLIENT
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CLONE_ESPLORACLIENT
void*_Nonnull uniffi_bdkffi_fn_clone_esploraclient(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_FREE_ESPLORACLIENT
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_FREE_ESPLORACLIENT
void uniffi_bdkffi_fn_free_esploraclient(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_ESPLORACLIENT_NEW
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_ESPLORACLIENT_NEW
void*_Nonnull uniffi_bdkffi_fn_constructor_esploraclient_new(RustBuffer url, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_ESPLORACLIENT_BROADCAST
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_ESPLORACLIENT_BROADCAST
void uniffi_bdkffi_fn_method_esploraclient_broadcast(void*_Nonnull ptr, void*_Nonnull transaction, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_ESPLORACLIENT_FULL_SCAN
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_ESPLORACLIENT_FULL_SCAN
void*_Nonnull uniffi_bdkffi_fn_method_esploraclient_full_scan(void*_Nonnull ptr, void*_Nonnull full_scan_request, uint64_t stop_gap, uint64_t parallel_requests, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_ESPLORACLIENT_SYNC
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_ESPLORACLIENT_SYNC
void*_Nonnull uniffi_bdkffi_fn_method_esploraclient_sync(void*_Nonnull ptr, void*_Nonnull sync_request, uint64_t parallel_requests, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CLONE_FEERATE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CLONE_FEERATE
void*_Nonnull uniffi_bdkffi_fn_clone_feerate(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_FREE_FEERATE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_FREE_FEERATE
void uniffi_bdkffi_fn_free_feerate(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_FEERATE_FROM_SAT_PER_KWU
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_FEERATE_FROM_SAT_PER_KWU
void*_Nonnull uniffi_bdkffi_fn_constructor_feerate_from_sat_per_kwu(uint64_t sat_per_kwu, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_FEERATE_FROM_SAT_PER_VB
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_FEERATE_FROM_SAT_PER_VB
void*_Nonnull uniffi_bdkffi_fn_constructor_feerate_from_sat_per_vb(uint64_t sat_per_vb, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_FEERATE_TO_SAT_PER_KWU
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_FEERATE_TO_SAT_PER_KWU
uint64_t uniffi_bdkffi_fn_method_feerate_to_sat_per_kwu(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_FEERATE_TO_SAT_PER_VB_CEIL
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_FEERATE_TO_SAT_PER_VB_CEIL
uint64_t uniffi_bdkffi_fn_method_feerate_to_sat_per_vb_ceil(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_FEERATE_TO_SAT_PER_VB_FLOOR
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_FEERATE_TO_SAT_PER_VB_FLOOR
uint64_t uniffi_bdkffi_fn_method_feerate_to_sat_per_vb_floor(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CLONE_FULLSCANREQUEST
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CLONE_FULLSCANREQUEST
void*_Nonnull uniffi_bdkffi_fn_clone_fullscanrequest(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_FREE_FULLSCANREQUEST
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_FREE_FULLSCANREQUEST
void uniffi_bdkffi_fn_free_fullscanrequest(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_FULLSCANREQUEST_INSPECT_SPKS_FOR_ALL_KEYCHAINS
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_FULLSCANREQUEST_INSPECT_SPKS_FOR_ALL_KEYCHAINS
void*_Nonnull uniffi_bdkffi_fn_method_fullscanrequest_inspect_spks_for_all_keychains(void*_Nonnull ptr, uint64_t inspector, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CLONE_MNEMONIC
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CLONE_MNEMONIC
void*_Nonnull uniffi_bdkffi_fn_clone_mnemonic(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_FREE_MNEMONIC
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_FREE_MNEMONIC
void uniffi_bdkffi_fn_free_mnemonic(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_MNEMONIC_FROM_ENTROPY
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_MNEMONIC_FROM_ENTROPY
void*_Nonnull uniffi_bdkffi_fn_constructor_mnemonic_from_entropy(RustBuffer entropy, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_MNEMONIC_FROM_STRING
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_MNEMONIC_FROM_STRING
void*_Nonnull uniffi_bdkffi_fn_constructor_mnemonic_from_string(RustBuffer mnemonic, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_MNEMONIC_NEW
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_MNEMONIC_NEW
void*_Nonnull uniffi_bdkffi_fn_constructor_mnemonic_new(RustBuffer word_count, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_MNEMONIC_AS_STRING
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_MNEMONIC_AS_STRING
RustBuffer uniffi_bdkffi_fn_method_mnemonic_as_string(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CLONE_PSBT
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CLONE_PSBT
void*_Nonnull uniffi_bdkffi_fn_clone_psbt(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_FREE_PSBT
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_FREE_PSBT
void uniffi_bdkffi_fn_free_psbt(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_PSBT_NEW
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_PSBT_NEW
void*_Nonnull uniffi_bdkffi_fn_constructor_psbt_new(RustBuffer psbt_base64, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_PSBT_COMBINE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_PSBT_COMBINE
void*_Nonnull uniffi_bdkffi_fn_method_psbt_combine(void*_Nonnull ptr, void*_Nonnull other, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_PSBT_EXTRACT_TX
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_PSBT_EXTRACT_TX
void*_Nonnull uniffi_bdkffi_fn_method_psbt_extract_tx(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_PSBT_FEE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_PSBT_FEE
uint64_t uniffi_bdkffi_fn_method_psbt_fee(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_PSBT_JSON_SERIALIZE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_PSBT_JSON_SERIALIZE
RustBuffer uniffi_bdkffi_fn_method_psbt_json_serialize(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_PSBT_SERIALIZE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_PSBT_SERIALIZE
RustBuffer uniffi_bdkffi_fn_method_psbt_serialize(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CLONE_SYNCREQUEST
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CLONE_SYNCREQUEST
void*_Nonnull uniffi_bdkffi_fn_clone_syncrequest(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_FREE_SYNCREQUEST
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_FREE_SYNCREQUEST
void uniffi_bdkffi_fn_free_syncrequest(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_SYNCREQUEST_INSPECT_SPKS
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_SYNCREQUEST_INSPECT_SPKS
void*_Nonnull uniffi_bdkffi_fn_method_syncrequest_inspect_spks(void*_Nonnull ptr, uint64_t inspector, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CLONE_TRANSACTION
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CLONE_TRANSACTION
void*_Nonnull uniffi_bdkffi_fn_clone_transaction(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_FREE_TRANSACTION
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_FREE_TRANSACTION
void uniffi_bdkffi_fn_free_transaction(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_TRANSACTION_NEW
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_TRANSACTION_NEW
void*_Nonnull uniffi_bdkffi_fn_constructor_transaction_new(RustBuffer transaction_bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TRANSACTION_INPUT
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TRANSACTION_INPUT
RustBuffer uniffi_bdkffi_fn_method_transaction_input(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TRANSACTION_IS_COINBASE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TRANSACTION_IS_COINBASE
int8_t uniffi_bdkffi_fn_method_transaction_is_coinbase(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TRANSACTION_IS_EXPLICITLY_RBF
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TRANSACTION_IS_EXPLICITLY_RBF
int8_t uniffi_bdkffi_fn_method_transaction_is_explicitly_rbf(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TRANSACTION_IS_LOCK_TIME_ENABLED
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TRANSACTION_IS_LOCK_TIME_ENABLED
int8_t uniffi_bdkffi_fn_method_transaction_is_lock_time_enabled(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TRANSACTION_LOCK_TIME
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TRANSACTION_LOCK_TIME
uint32_t uniffi_bdkffi_fn_method_transaction_lock_time(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TRANSACTION_OUTPUT
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TRANSACTION_OUTPUT
RustBuffer uniffi_bdkffi_fn_method_transaction_output(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TRANSACTION_SERIALIZE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TRANSACTION_SERIALIZE
RustBuffer uniffi_bdkffi_fn_method_transaction_serialize(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TRANSACTION_TOTAL_SIZE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TRANSACTION_TOTAL_SIZE
uint64_t uniffi_bdkffi_fn_method_transaction_total_size(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TRANSACTION_TXID
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TRANSACTION_TXID
RustBuffer uniffi_bdkffi_fn_method_transaction_txid(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TRANSACTION_VERSION
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TRANSACTION_VERSION
int32_t uniffi_bdkffi_fn_method_transaction_version(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TRANSACTION_VSIZE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TRANSACTION_VSIZE
uint64_t uniffi_bdkffi_fn_method_transaction_vsize(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TRANSACTION_WEIGHT
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TRANSACTION_WEIGHT
uint64_t uniffi_bdkffi_fn_method_transaction_weight(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CLONE_TXBUILDER
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CLONE_TXBUILDER
void*_Nonnull uniffi_bdkffi_fn_clone_txbuilder(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_FREE_TXBUILDER
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_FREE_TXBUILDER
void uniffi_bdkffi_fn_free_txbuilder(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_TXBUILDER_NEW
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_TXBUILDER_NEW
void*_Nonnull uniffi_bdkffi_fn_constructor_txbuilder_new(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TXBUILDER_ADD_RECIPIENT
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TXBUILDER_ADD_RECIPIENT
void*_Nonnull uniffi_bdkffi_fn_method_txbuilder_add_recipient(void*_Nonnull ptr, void*_Nonnull script, void*_Nonnull amount, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TXBUILDER_ADD_UNSPENDABLE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TXBUILDER_ADD_UNSPENDABLE
void*_Nonnull uniffi_bdkffi_fn_method_txbuilder_add_unspendable(void*_Nonnull ptr, RustBuffer unspendable, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TXBUILDER_ADD_UTXO
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TXBUILDER_ADD_UTXO
void*_Nonnull uniffi_bdkffi_fn_method_txbuilder_add_utxo(void*_Nonnull ptr, RustBuffer outpoint, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TXBUILDER_CHANGE_POLICY
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TXBUILDER_CHANGE_POLICY
void*_Nonnull uniffi_bdkffi_fn_method_txbuilder_change_policy(void*_Nonnull ptr, RustBuffer change_policy, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TXBUILDER_DO_NOT_SPEND_CHANGE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TXBUILDER_DO_NOT_SPEND_CHANGE
void*_Nonnull uniffi_bdkffi_fn_method_txbuilder_do_not_spend_change(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TXBUILDER_DRAIN_TO
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TXBUILDER_DRAIN_TO
void*_Nonnull uniffi_bdkffi_fn_method_txbuilder_drain_to(void*_Nonnull ptr, void*_Nonnull script, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TXBUILDER_DRAIN_WALLET
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TXBUILDER_DRAIN_WALLET
void*_Nonnull uniffi_bdkffi_fn_method_txbuilder_drain_wallet(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TXBUILDER_ENABLE_RBF
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TXBUILDER_ENABLE_RBF
void*_Nonnull uniffi_bdkffi_fn_method_txbuilder_enable_rbf(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TXBUILDER_ENABLE_RBF_WITH_SEQUENCE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TXBUILDER_ENABLE_RBF_WITH_SEQUENCE
void*_Nonnull uniffi_bdkffi_fn_method_txbuilder_enable_rbf_with_sequence(void*_Nonnull ptr, uint32_t nsequence, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TXBUILDER_FEE_ABSOLUTE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TXBUILDER_FEE_ABSOLUTE
void*_Nonnull uniffi_bdkffi_fn_method_txbuilder_fee_absolute(void*_Nonnull ptr, uint64_t fee, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TXBUILDER_FEE_RATE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TXBUILDER_FEE_RATE
void*_Nonnull uniffi_bdkffi_fn_method_txbuilder_fee_rate(void*_Nonnull ptr, void*_Nonnull fee_rate, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TXBUILDER_FINISH
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TXBUILDER_FINISH
void*_Nonnull uniffi_bdkffi_fn_method_txbuilder_finish(void*_Nonnull ptr, void*_Nonnull wallet, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TXBUILDER_MANUALLY_SELECTED_ONLY
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TXBUILDER_MANUALLY_SELECTED_ONLY
void*_Nonnull uniffi_bdkffi_fn_method_txbuilder_manually_selected_only(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TXBUILDER_ONLY_SPEND_CHANGE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TXBUILDER_ONLY_SPEND_CHANGE
void*_Nonnull uniffi_bdkffi_fn_method_txbuilder_only_spend_change(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TXBUILDER_SET_RECIPIENTS
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TXBUILDER_SET_RECIPIENTS
void*_Nonnull uniffi_bdkffi_fn_method_txbuilder_set_recipients(void*_Nonnull ptr, RustBuffer recipients, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TXBUILDER_UNSPENDABLE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_TXBUILDER_UNSPENDABLE
void*_Nonnull uniffi_bdkffi_fn_method_txbuilder_unspendable(void*_Nonnull ptr, RustBuffer unspendable, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CLONE_UPDATE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CLONE_UPDATE
void*_Nonnull uniffi_bdkffi_fn_clone_update(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_FREE_UPDATE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_FREE_UPDATE
void uniffi_bdkffi_fn_free_update(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CLONE_WALLET
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CLONE_WALLET
void*_Nonnull uniffi_bdkffi_fn_clone_wallet(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_FREE_WALLET
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_FREE_WALLET
void uniffi_bdkffi_fn_free_wallet(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_WALLET_NEW
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_WALLET_NEW
void*_Nonnull uniffi_bdkffi_fn_constructor_wallet_new(void*_Nonnull descriptor, RustBuffer change_descriptor, RustBuffer persistence_backend_path, RustBuffer network, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_WALLET_NEW_NO_PERSIST
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_CONSTRUCTOR_WALLET_NEW_NO_PERSIST
void*_Nonnull uniffi_bdkffi_fn_constructor_wallet_new_no_persist(void*_Nonnull descriptor, RustBuffer change_descriptor, RustBuffer network, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_WALLET_APPLY_UPDATE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_WALLET_APPLY_UPDATE
void uniffi_bdkffi_fn_method_wallet_apply_update(void*_Nonnull ptr, void*_Nonnull update, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_WALLET_CALCULATE_FEE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_WALLET_CALCULATE_FEE
uint64_t uniffi_bdkffi_fn_method_wallet_calculate_fee(void*_Nonnull ptr, void*_Nonnull tx, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_WALLET_CALCULATE_FEE_RATE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_WALLET_CALCULATE_FEE_RATE
void*_Nonnull uniffi_bdkffi_fn_method_wallet_calculate_fee_rate(void*_Nonnull ptr, void*_Nonnull tx, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_WALLET_COMMIT
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_WALLET_COMMIT
int8_t uniffi_bdkffi_fn_method_wallet_commit(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_WALLET_GET_BALANCE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_WALLET_GET_BALANCE
RustBuffer uniffi_bdkffi_fn_method_wallet_get_balance(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_WALLET_GET_TX
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_WALLET_GET_TX
RustBuffer uniffi_bdkffi_fn_method_wallet_get_tx(void*_Nonnull ptr, RustBuffer txid, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_WALLET_IS_MINE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_WALLET_IS_MINE
int8_t uniffi_bdkffi_fn_method_wallet_is_mine(void*_Nonnull ptr, void*_Nonnull script, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_WALLET_LIST_OUTPUT
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_WALLET_LIST_OUTPUT
RustBuffer uniffi_bdkffi_fn_method_wallet_list_output(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_WALLET_LIST_UNSPENT
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_WALLET_LIST_UNSPENT
RustBuffer uniffi_bdkffi_fn_method_wallet_list_unspent(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_WALLET_NETWORK
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_WALLET_NETWORK
RustBuffer uniffi_bdkffi_fn_method_wallet_network(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_WALLET_REVEAL_NEXT_ADDRESS
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_WALLET_REVEAL_NEXT_ADDRESS
RustBuffer uniffi_bdkffi_fn_method_wallet_reveal_next_address(void*_Nonnull ptr, RustBuffer keychain, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_WALLET_SENT_AND_RECEIVED
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_WALLET_SENT_AND_RECEIVED
RustBuffer uniffi_bdkffi_fn_method_wallet_sent_and_received(void*_Nonnull ptr, void*_Nonnull tx, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_WALLET_SIGN
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_WALLET_SIGN
int8_t uniffi_bdkffi_fn_method_wallet_sign(void*_Nonnull ptr, void*_Nonnull psbt, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_WALLET_START_FULL_SCAN
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_WALLET_START_FULL_SCAN
void*_Nonnull uniffi_bdkffi_fn_method_wallet_start_full_scan(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_WALLET_START_SYNC_WITH_REVEALED_SPKS
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_WALLET_START_SYNC_WITH_REVEALED_SPKS
void*_Nonnull uniffi_bdkffi_fn_method_wallet_start_sync_with_revealed_spks(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_WALLET_TRANSACTIONS
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_METHOD_WALLET_TRANSACTIONS
RustBuffer uniffi_bdkffi_fn_method_wallet_transactions(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_INIT_CALLBACK_VTABLE_FULLSCANSCRIPTINSPECTOR
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_INIT_CALLBACK_VTABLE_FULLSCANSCRIPTINSPECTOR
void uniffi_bdkffi_fn_init_callback_vtable_fullscanscriptinspector(UniffiVTableCallbackInterfaceFullScanScriptInspector* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_INIT_CALLBACK_VTABLE_SYNCSCRIPTINSPECTOR
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_FN_INIT_CALLBACK_VTABLE_SYNCSCRIPTINSPECTOR
void uniffi_bdkffi_fn_init_callback_vtable_syncscriptinspector(UniffiVTableCallbackInterfaceSyncScriptInspector* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUSTBUFFER_ALLOC
RustBuffer ffi_bdkffi_rustbuffer_alloc(uint64_t size, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_bdkffi_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUSTBUFFER_FREE
void ffi_bdkffi_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUSTBUFFER_RESERVE
RustBuffer ffi_bdkffi_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_POLL_U8
void ffi_bdkffi_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_CANCEL_U8
void ffi_bdkffi_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_FREE_U8
void ffi_bdkffi_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_bdkffi_rust_future_complete_u8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_POLL_I8
void ffi_bdkffi_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_CANCEL_I8
void ffi_bdkffi_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_FREE_I8
void ffi_bdkffi_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_COMPLETE_I8
int8_t ffi_bdkffi_rust_future_complete_i8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_POLL_U16
void ffi_bdkffi_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_CANCEL_U16
void ffi_bdkffi_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_FREE_U16
void ffi_bdkffi_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_bdkffi_rust_future_complete_u16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_POLL_I16
void ffi_bdkffi_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_CANCEL_I16
void ffi_bdkffi_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_FREE_I16
void ffi_bdkffi_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_COMPLETE_I16
int16_t ffi_bdkffi_rust_future_complete_i16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_POLL_U32
void ffi_bdkffi_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_CANCEL_U32
void ffi_bdkffi_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_FREE_U32
void ffi_bdkffi_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_bdkffi_rust_future_complete_u32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_POLL_I32
void ffi_bdkffi_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_CANCEL_I32
void ffi_bdkffi_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_FREE_I32
void ffi_bdkffi_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_COMPLETE_I32
int32_t ffi_bdkffi_rust_future_complete_i32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_POLL_U64
void ffi_bdkffi_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_CANCEL_U64
void ffi_bdkffi_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_FREE_U64
void ffi_bdkffi_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_bdkffi_rust_future_complete_u64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_POLL_I64
void ffi_bdkffi_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_CANCEL_I64
void ffi_bdkffi_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_FREE_I64
void ffi_bdkffi_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_COMPLETE_I64
int64_t ffi_bdkffi_rust_future_complete_i64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_POLL_F32
void ffi_bdkffi_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_CANCEL_F32
void ffi_bdkffi_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_FREE_F32
void ffi_bdkffi_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_COMPLETE_F32
float ffi_bdkffi_rust_future_complete_f32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_POLL_F64
void ffi_bdkffi_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_CANCEL_F64
void ffi_bdkffi_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_FREE_F64
void ffi_bdkffi_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_COMPLETE_F64
double ffi_bdkffi_rust_future_complete_f64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_POLL_POINTER
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_POLL_POINTER
void ffi_bdkffi_rust_future_poll_pointer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_CANCEL_POINTER
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_CANCEL_POINTER
void ffi_bdkffi_rust_future_cancel_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_FREE_POINTER
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_FREE_POINTER
void ffi_bdkffi_rust_future_free_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_COMPLETE_POINTER
void*_Nonnull ffi_bdkffi_rust_future_complete_pointer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_bdkffi_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_bdkffi_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_bdkffi_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_bdkffi_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_POLL_VOID
void ffi_bdkffi_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_CANCEL_VOID
void ffi_bdkffi_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_FREE_VOID
void ffi_bdkffi_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_BDKFFI_RUST_FUTURE_COMPLETE_VOID
void ffi_bdkffi_rust_future_complete_void(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_ADDRESS_AS_STRING
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_ADDRESS_AS_STRING
uint16_t uniffi_bdkffi_checksum_method_address_as_string(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_ADDRESS_IS_VALID_FOR_NETWORK
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_ADDRESS_IS_VALID_FOR_NETWORK
uint16_t uniffi_bdkffi_checksum_method_address_is_valid_for_network(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_ADDRESS_NETWORK
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_ADDRESS_NETWORK
uint16_t uniffi_bdkffi_checksum_method_address_network(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_ADDRESS_SCRIPT_PUBKEY
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_ADDRESS_SCRIPT_PUBKEY
uint16_t uniffi_bdkffi_checksum_method_address_script_pubkey(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_ADDRESS_TO_QR_URI
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_ADDRESS_TO_QR_URI
uint16_t uniffi_bdkffi_checksum_method_address_to_qr_uri(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_AMOUNT_TO_BTC
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_AMOUNT_TO_BTC
uint16_t uniffi_bdkffi_checksum_method_amount_to_btc(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_AMOUNT_TO_SAT
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_AMOUNT_TO_SAT
uint16_t uniffi_bdkffi_checksum_method_amount_to_sat(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_BUMPFEETXBUILDER_ENABLE_RBF
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_BUMPFEETXBUILDER_ENABLE_RBF
uint16_t uniffi_bdkffi_checksum_method_bumpfeetxbuilder_enable_rbf(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_BUMPFEETXBUILDER_ENABLE_RBF_WITH_SEQUENCE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_BUMPFEETXBUILDER_ENABLE_RBF_WITH_SEQUENCE
uint16_t uniffi_bdkffi_checksum_method_bumpfeetxbuilder_enable_rbf_with_sequence(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_BUMPFEETXBUILDER_FINISH
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_BUMPFEETXBUILDER_FINISH
uint16_t uniffi_bdkffi_checksum_method_bumpfeetxbuilder_finish(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_DESCRIPTOR_AS_STRING
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_DESCRIPTOR_AS_STRING
uint16_t uniffi_bdkffi_checksum_method_descriptor_as_string(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_DESCRIPTOR_AS_STRING_PRIVATE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_DESCRIPTOR_AS_STRING_PRIVATE
uint16_t uniffi_bdkffi_checksum_method_descriptor_as_string_private(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_DESCRIPTORPUBLICKEY_AS_STRING
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_DESCRIPTORPUBLICKEY_AS_STRING
uint16_t uniffi_bdkffi_checksum_method_descriptorpublickey_as_string(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_DESCRIPTORPUBLICKEY_DERIVE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_DESCRIPTORPUBLICKEY_DERIVE
uint16_t uniffi_bdkffi_checksum_method_descriptorpublickey_derive(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_DESCRIPTORPUBLICKEY_EXTEND
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_DESCRIPTORPUBLICKEY_EXTEND
uint16_t uniffi_bdkffi_checksum_method_descriptorpublickey_extend(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_DESCRIPTORSECRETKEY_AS_PUBLIC
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_DESCRIPTORSECRETKEY_AS_PUBLIC
uint16_t uniffi_bdkffi_checksum_method_descriptorsecretkey_as_public(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_DESCRIPTORSECRETKEY_AS_STRING
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_DESCRIPTORSECRETKEY_AS_STRING
uint16_t uniffi_bdkffi_checksum_method_descriptorsecretkey_as_string(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_DESCRIPTORSECRETKEY_DERIVE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_DESCRIPTORSECRETKEY_DERIVE
uint16_t uniffi_bdkffi_checksum_method_descriptorsecretkey_derive(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_DESCRIPTORSECRETKEY_EXTEND
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_DESCRIPTORSECRETKEY_EXTEND
uint16_t uniffi_bdkffi_checksum_method_descriptorsecretkey_extend(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_DESCRIPTORSECRETKEY_SECRET_BYTES
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_DESCRIPTORSECRETKEY_SECRET_BYTES
uint16_t uniffi_bdkffi_checksum_method_descriptorsecretkey_secret_bytes(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_ELECTRUMCLIENT_BROADCAST
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_ELECTRUMCLIENT_BROADCAST
uint16_t uniffi_bdkffi_checksum_method_electrumclient_broadcast(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_ELECTRUMCLIENT_FULL_SCAN
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_ELECTRUMCLIENT_FULL_SCAN
uint16_t uniffi_bdkffi_checksum_method_electrumclient_full_scan(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_ELECTRUMCLIENT_SYNC
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_ELECTRUMCLIENT_SYNC
uint16_t uniffi_bdkffi_checksum_method_electrumclient_sync(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_ESPLORACLIENT_BROADCAST
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_ESPLORACLIENT_BROADCAST
uint16_t uniffi_bdkffi_checksum_method_esploraclient_broadcast(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_ESPLORACLIENT_FULL_SCAN
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_ESPLORACLIENT_FULL_SCAN
uint16_t uniffi_bdkffi_checksum_method_esploraclient_full_scan(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_ESPLORACLIENT_SYNC
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_ESPLORACLIENT_SYNC
uint16_t uniffi_bdkffi_checksum_method_esploraclient_sync(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_FEERATE_TO_SAT_PER_KWU
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_FEERATE_TO_SAT_PER_KWU
uint16_t uniffi_bdkffi_checksum_method_feerate_to_sat_per_kwu(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_FEERATE_TO_SAT_PER_VB_CEIL
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_FEERATE_TO_SAT_PER_VB_CEIL
uint16_t uniffi_bdkffi_checksum_method_feerate_to_sat_per_vb_ceil(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_FEERATE_TO_SAT_PER_VB_FLOOR
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_FEERATE_TO_SAT_PER_VB_FLOOR
uint16_t uniffi_bdkffi_checksum_method_feerate_to_sat_per_vb_floor(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_FULLSCANREQUEST_INSPECT_SPKS_FOR_ALL_KEYCHAINS
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_FULLSCANREQUEST_INSPECT_SPKS_FOR_ALL_KEYCHAINS
uint16_t uniffi_bdkffi_checksum_method_fullscanrequest_inspect_spks_for_all_keychains(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_MNEMONIC_AS_STRING
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_MNEMONIC_AS_STRING
uint16_t uniffi_bdkffi_checksum_method_mnemonic_as_string(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_PSBT_COMBINE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_PSBT_COMBINE
uint16_t uniffi_bdkffi_checksum_method_psbt_combine(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_PSBT_EXTRACT_TX
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_PSBT_EXTRACT_TX
uint16_t uniffi_bdkffi_checksum_method_psbt_extract_tx(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_PSBT_FEE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_PSBT_FEE
uint16_t uniffi_bdkffi_checksum_method_psbt_fee(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_PSBT_JSON_SERIALIZE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_PSBT_JSON_SERIALIZE
uint16_t uniffi_bdkffi_checksum_method_psbt_json_serialize(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_PSBT_SERIALIZE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_PSBT_SERIALIZE
uint16_t uniffi_bdkffi_checksum_method_psbt_serialize(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_SYNCREQUEST_INSPECT_SPKS
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_SYNCREQUEST_INSPECT_SPKS
uint16_t uniffi_bdkffi_checksum_method_syncrequest_inspect_spks(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TRANSACTION_INPUT
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TRANSACTION_INPUT
uint16_t uniffi_bdkffi_checksum_method_transaction_input(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TRANSACTION_IS_COINBASE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TRANSACTION_IS_COINBASE
uint16_t uniffi_bdkffi_checksum_method_transaction_is_coinbase(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TRANSACTION_IS_EXPLICITLY_RBF
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TRANSACTION_IS_EXPLICITLY_RBF
uint16_t uniffi_bdkffi_checksum_method_transaction_is_explicitly_rbf(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TRANSACTION_IS_LOCK_TIME_ENABLED
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TRANSACTION_IS_LOCK_TIME_ENABLED
uint16_t uniffi_bdkffi_checksum_method_transaction_is_lock_time_enabled(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TRANSACTION_LOCK_TIME
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TRANSACTION_LOCK_TIME
uint16_t uniffi_bdkffi_checksum_method_transaction_lock_time(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TRANSACTION_OUTPUT
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TRANSACTION_OUTPUT
uint16_t uniffi_bdkffi_checksum_method_transaction_output(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TRANSACTION_SERIALIZE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TRANSACTION_SERIALIZE
uint16_t uniffi_bdkffi_checksum_method_transaction_serialize(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TRANSACTION_TOTAL_SIZE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TRANSACTION_TOTAL_SIZE
uint16_t uniffi_bdkffi_checksum_method_transaction_total_size(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TRANSACTION_TXID
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TRANSACTION_TXID
uint16_t uniffi_bdkffi_checksum_method_transaction_txid(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TRANSACTION_VERSION
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TRANSACTION_VERSION
uint16_t uniffi_bdkffi_checksum_method_transaction_version(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TRANSACTION_VSIZE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TRANSACTION_VSIZE
uint16_t uniffi_bdkffi_checksum_method_transaction_vsize(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TRANSACTION_WEIGHT
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TRANSACTION_WEIGHT
uint16_t uniffi_bdkffi_checksum_method_transaction_weight(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TXBUILDER_ADD_RECIPIENT
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TXBUILDER_ADD_RECIPIENT
uint16_t uniffi_bdkffi_checksum_method_txbuilder_add_recipient(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TXBUILDER_ADD_UNSPENDABLE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TXBUILDER_ADD_UNSPENDABLE
uint16_t uniffi_bdkffi_checksum_method_txbuilder_add_unspendable(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TXBUILDER_ADD_UTXO
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TXBUILDER_ADD_UTXO
uint16_t uniffi_bdkffi_checksum_method_txbuilder_add_utxo(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TXBUILDER_CHANGE_POLICY
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TXBUILDER_CHANGE_POLICY
uint16_t uniffi_bdkffi_checksum_method_txbuilder_change_policy(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TXBUILDER_DO_NOT_SPEND_CHANGE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TXBUILDER_DO_NOT_SPEND_CHANGE
uint16_t uniffi_bdkffi_checksum_method_txbuilder_do_not_spend_change(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TXBUILDER_DRAIN_TO
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TXBUILDER_DRAIN_TO
uint16_t uniffi_bdkffi_checksum_method_txbuilder_drain_to(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TXBUILDER_DRAIN_WALLET
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TXBUILDER_DRAIN_WALLET
uint16_t uniffi_bdkffi_checksum_method_txbuilder_drain_wallet(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TXBUILDER_ENABLE_RBF
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TXBUILDER_ENABLE_RBF
uint16_t uniffi_bdkffi_checksum_method_txbuilder_enable_rbf(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TXBUILDER_ENABLE_RBF_WITH_SEQUENCE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TXBUILDER_ENABLE_RBF_WITH_SEQUENCE
uint16_t uniffi_bdkffi_checksum_method_txbuilder_enable_rbf_with_sequence(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TXBUILDER_FEE_ABSOLUTE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TXBUILDER_FEE_ABSOLUTE
uint16_t uniffi_bdkffi_checksum_method_txbuilder_fee_absolute(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TXBUILDER_FEE_RATE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TXBUILDER_FEE_RATE
uint16_t uniffi_bdkffi_checksum_method_txbuilder_fee_rate(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TXBUILDER_FINISH
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TXBUILDER_FINISH
uint16_t uniffi_bdkffi_checksum_method_txbuilder_finish(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TXBUILDER_MANUALLY_SELECTED_ONLY
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TXBUILDER_MANUALLY_SELECTED_ONLY
uint16_t uniffi_bdkffi_checksum_method_txbuilder_manually_selected_only(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TXBUILDER_ONLY_SPEND_CHANGE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TXBUILDER_ONLY_SPEND_CHANGE
uint16_t uniffi_bdkffi_checksum_method_txbuilder_only_spend_change(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TXBUILDER_SET_RECIPIENTS
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TXBUILDER_SET_RECIPIENTS
uint16_t uniffi_bdkffi_checksum_method_txbuilder_set_recipients(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TXBUILDER_UNSPENDABLE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_TXBUILDER_UNSPENDABLE
uint16_t uniffi_bdkffi_checksum_method_txbuilder_unspendable(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_WALLET_APPLY_UPDATE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_WALLET_APPLY_UPDATE
uint16_t uniffi_bdkffi_checksum_method_wallet_apply_update(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_WALLET_CALCULATE_FEE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_WALLET_CALCULATE_FEE
uint16_t uniffi_bdkffi_checksum_method_wallet_calculate_fee(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_WALLET_CALCULATE_FEE_RATE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_WALLET_CALCULATE_FEE_RATE
uint16_t uniffi_bdkffi_checksum_method_wallet_calculate_fee_rate(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_WALLET_COMMIT
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_WALLET_COMMIT
uint16_t uniffi_bdkffi_checksum_method_wallet_commit(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_WALLET_GET_BALANCE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_WALLET_GET_BALANCE
uint16_t uniffi_bdkffi_checksum_method_wallet_get_balance(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_WALLET_GET_TX
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_WALLET_GET_TX
uint16_t uniffi_bdkffi_checksum_method_wallet_get_tx(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_WALLET_IS_MINE
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_WALLET_IS_MINE
uint16_t uniffi_bdkffi_checksum_method_wallet_is_mine(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_WALLET_LIST_OUTPUT
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_WALLET_LIST_OUTPUT
uint16_t uniffi_bdkffi_checksum_method_wallet_list_output(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_WALLET_LIST_UNSPENT
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_WALLET_LIST_UNSPENT
uint16_t uniffi_bdkffi_checksum_method_wallet_list_unspent(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_WALLET_NETWORK
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_WALLET_NETWORK
uint16_t uniffi_bdkffi_checksum_method_wallet_network(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_WALLET_REVEAL_NEXT_ADDRESS
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_WALLET_REVEAL_NEXT_ADDRESS
uint16_t uniffi_bdkffi_checksum_method_wallet_reveal_next_address(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_WALLET_SENT_AND_RECEIVED
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_WALLET_SENT_AND_RECEIVED
uint16_t uniffi_bdkffi_checksum_method_wallet_sent_and_received(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_WALLET_SIGN
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_WALLET_SIGN
uint16_t uniffi_bdkffi_checksum_method_wallet_sign(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_WALLET_START_FULL_SCAN
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_WALLET_START_FULL_SCAN
uint16_t uniffi_bdkffi_checksum_method_wallet_start_full_scan(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_WALLET_START_SYNC_WITH_REVEALED_SPKS
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_WALLET_START_SYNC_WITH_REVEALED_SPKS
uint16_t uniffi_bdkffi_checksum_method_wallet_start_sync_with_revealed_spks(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_WALLET_TRANSACTIONS
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_WALLET_TRANSACTIONS
uint16_t uniffi_bdkffi_checksum_method_wallet_transactions(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_ADDRESS_NEW
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_ADDRESS_NEW
uint16_t uniffi_bdkffi_checksum_constructor_address_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_AMOUNT_FROM_BTC
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_AMOUNT_FROM_BTC
uint16_t uniffi_bdkffi_checksum_constructor_amount_from_btc(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_AMOUNT_FROM_SAT
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_AMOUNT_FROM_SAT
uint16_t uniffi_bdkffi_checksum_constructor_amount_from_sat(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_BUMPFEETXBUILDER_NEW
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_BUMPFEETXBUILDER_NEW
uint16_t uniffi_bdkffi_checksum_constructor_bumpfeetxbuilder_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_DERIVATIONPATH_NEW
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_DERIVATIONPATH_NEW
uint16_t uniffi_bdkffi_checksum_constructor_derivationpath_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_DESCRIPTOR_NEW
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_DESCRIPTOR_NEW
uint16_t uniffi_bdkffi_checksum_constructor_descriptor_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_DESCRIPTOR_NEW_BIP44
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_DESCRIPTOR_NEW_BIP44
uint16_t uniffi_bdkffi_checksum_constructor_descriptor_new_bip44(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_DESCRIPTOR_NEW_BIP44_PUBLIC
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_DESCRIPTOR_NEW_BIP44_PUBLIC
uint16_t uniffi_bdkffi_checksum_constructor_descriptor_new_bip44_public(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_DESCRIPTOR_NEW_BIP49
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_DESCRIPTOR_NEW_BIP49
uint16_t uniffi_bdkffi_checksum_constructor_descriptor_new_bip49(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_DESCRIPTOR_NEW_BIP49_PUBLIC
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_DESCRIPTOR_NEW_BIP49_PUBLIC
uint16_t uniffi_bdkffi_checksum_constructor_descriptor_new_bip49_public(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_DESCRIPTOR_NEW_BIP84
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_DESCRIPTOR_NEW_BIP84
uint16_t uniffi_bdkffi_checksum_constructor_descriptor_new_bip84(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_DESCRIPTOR_NEW_BIP84_PUBLIC
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_DESCRIPTOR_NEW_BIP84_PUBLIC
uint16_t uniffi_bdkffi_checksum_constructor_descriptor_new_bip84_public(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_DESCRIPTOR_NEW_BIP86
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_DESCRIPTOR_NEW_BIP86
uint16_t uniffi_bdkffi_checksum_constructor_descriptor_new_bip86(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_DESCRIPTOR_NEW_BIP86_PUBLIC
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_DESCRIPTOR_NEW_BIP86_PUBLIC
uint16_t uniffi_bdkffi_checksum_constructor_descriptor_new_bip86_public(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_DESCRIPTORPUBLICKEY_FROM_STRING
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_DESCRIPTORPUBLICKEY_FROM_STRING
uint16_t uniffi_bdkffi_checksum_constructor_descriptorpublickey_from_string(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_DESCRIPTORSECRETKEY_FROM_STRING
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_DESCRIPTORSECRETKEY_FROM_STRING
uint16_t uniffi_bdkffi_checksum_constructor_descriptorsecretkey_from_string(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_DESCRIPTORSECRETKEY_NEW
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_DESCRIPTORSECRETKEY_NEW
uint16_t uniffi_bdkffi_checksum_constructor_descriptorsecretkey_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_ELECTRUMCLIENT_NEW
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_ELECTRUMCLIENT_NEW
uint16_t uniffi_bdkffi_checksum_constructor_electrumclient_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_ESPLORACLIENT_NEW
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_ESPLORACLIENT_NEW
uint16_t uniffi_bdkffi_checksum_constructor_esploraclient_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_FEERATE_FROM_SAT_PER_KWU
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_FEERATE_FROM_SAT_PER_KWU
uint16_t uniffi_bdkffi_checksum_constructor_feerate_from_sat_per_kwu(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_FEERATE_FROM_SAT_PER_VB
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_FEERATE_FROM_SAT_PER_VB
uint16_t uniffi_bdkffi_checksum_constructor_feerate_from_sat_per_vb(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_MNEMONIC_FROM_ENTROPY
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_MNEMONIC_FROM_ENTROPY
uint16_t uniffi_bdkffi_checksum_constructor_mnemonic_from_entropy(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_MNEMONIC_FROM_STRING
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_MNEMONIC_FROM_STRING
uint16_t uniffi_bdkffi_checksum_constructor_mnemonic_from_string(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_MNEMONIC_NEW
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_MNEMONIC_NEW
uint16_t uniffi_bdkffi_checksum_constructor_mnemonic_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_PSBT_NEW
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_PSBT_NEW
uint16_t uniffi_bdkffi_checksum_constructor_psbt_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_TRANSACTION_NEW
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_TRANSACTION_NEW
uint16_t uniffi_bdkffi_checksum_constructor_transaction_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_TXBUILDER_NEW
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_TXBUILDER_NEW
uint16_t uniffi_bdkffi_checksum_constructor_txbuilder_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_WALLET_NEW
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_WALLET_NEW
uint16_t uniffi_bdkffi_checksum_constructor_wallet_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_WALLET_NEW_NO_PERSIST
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_CONSTRUCTOR_WALLET_NEW_NO_PERSIST
uint16_t uniffi_bdkffi_checksum_constructor_wallet_new_no_persist(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_FULLSCANSCRIPTINSPECTOR_INSPECT
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_FULLSCANSCRIPTINSPECTOR_INSPECT
uint16_t uniffi_bdkffi_checksum_method_fullscanscriptinspector_inspect(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_SYNCSCRIPTINSPECTOR_INSPECT
#define UNIFFI_FFIDEF_UNIFFI_BDKFFI_CHECKSUM_METHOD_SYNCSCRIPTINSPECTOR_INSPECT
uint16_t uniffi_bdkffi_checksum_method_syncscriptinspector_inspect(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_BDKFFI_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_BDKFFI_UNIFFI_CONTRACT_VERSION
uint32_t ffi_bdkffi_uniffi_contract_version(void
    
);
#endif

