default:
  just --list

build-linux:
  bash ./scripts/build-linux-x86_64.sh

build-macos:
  bash ./scripts/build-macos-aarch64.sh

clean:
  rm -rf ../bdk-ffi/target/
  rm -rf ./build/
  rm -rf ./lib/build/
  rm -rf ./plugins/build/

publish-local:
  ./gradlew publishToMavenLocal -P localBuild

test:
  ./gradlew connectedAndroidTest

test-specific TEST:
  ./gradlew test --tests {{TEST}}
