test:
  ./gradlew connectedAndroidTest

onetest TEST:
  ./gradlew test --tests {{TEST}}

build:
  ./gradlew buildAndroidLib

publishlocal:
  ./gradlew publishToMavenLocal -P localBuild

clean:
  rm -rf ../bdk-ffi/target/
  rm -rf ./build/
  rm -rf ./lib/build/
  rm -rf ./plugins/build/