default:
  just --list

build:
  cargo build --locked --profile release-smaller

build-dev:
  cargo build --locked

check:
   cargo fmt
   cargo clippy --locked

test:
  cargo test --locked

# Build API documentation for gh-pages or local browsing
docs:
  bash scripts/build-docs.sh && bash scripts/deploy-docs.sh
