[bindings.kotlin]
package_name = "org.bitcoindevkit"
cdylib_name = "bdkffi"

[bindings.python]
cdylib_name = "bdkffi"

[bindings.swift]
module_name = "BitcoinDevKit"
cdylib_name = "bdkffi"

[bindings.kotlin.external_packages]
# Map the crate names from [External={name}] into Kotlin package names
bitcoin_ffi = "org.bitcoindevkit.bitcoinffi"
