name: Build Python API Docs Website

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Set up Python"
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.x'

      - name: "Install dependencies"
        run: |
          cd ./bdk-python/
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install sphinx sphinx-rtd-theme

      - name: "Build Python API documentation"
        run: |
          cd ./bdk-python/
          python scripts/generate_docs.py
          sphinx-build -b  html -W --keep-going  docs/ docs/_build/html 

#      - name: "Upload Python website"
#        uses: actions/upload-artifact@v4
#        with:
#          name: artifact-python-api-docs
#          path: /home/runner/work/bdk-ffi/bdk-ffi/bdk-python/docs/_build/html/
